use_frameworks!

platform :ios, '9.0'

target 'QMZhugeManger_Example' do
  pod 'QMZhugeManger', :path => '../'
  pod 'ZhugeioAnalytics'

  
  target 'QMZhugeManger_Tests' do
    inherit! :search_paths

    
  end
end
